<a href="https://colab.research.google.com/github/srivastavaaradhya2004-star/collab/blob/main/day_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**numpy**



In [1]:
import numpy as np

In [2]:
l=[1,2,3,4]

In [7]:
type(l)

list

In [5]:
ar=np.array(l)

In [6]:
ar

array([1, 2, 3, 4])

In [8]:
type(ar)

numpy.ndarray

In [9]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [10]:
np.asarray(l)

array([1, 2, 3, 4])

In [12]:
a=[2,3,4]

In [13]:
np.asanyarray(a)

array([2, 3, 4])

In [14]:
b=np.matrix(l)

In [15]:
b

matrix([[1, 2, 3, 4]])